// ANGULAR/hw3/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: false,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'hw3';
}

<h1>Hello, {{ title }}</h1>
<hr>
<app-users></app-users>
<app-posts></app-posts>
<app-comments></app-comments>

// REACT/hw4/src/App.jsx
import { useState } from 'react'
import HomeworkPage from './components/HomeworkPage'

import Users from './components/Users'
import Posts from './components/Posts'
import Comments from './components/Comments'

import Content from './components/Content'
import './App.css'

function App() {
  
  return (
    
      <div>
        <HomeworkPage/>
        <Users/>
        <Posts/>
        <Comments/>
        <Content/>
      </div>
      
  )
}

export default App
